# Generated by Django 2.1.2 on 2021-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_telegram', models.TextField(verbose_name='Телеграмм')),
                ('code', models.TextField(unique=True, verbose_name='Код потверждения')),
            ],
        ),
    ]
