# Generated by Django 2.1.2 on 2021-11-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='Code_2auth',
        ),
    ]
