# Generated by Django 2.1.2 on 2021-12-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211207_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_2auth',
            name='valide_token',
            field=models.TextField(default=['q', 'o', '7', 'd', 'r', 'v', 'b', ']', 'R', 'f', 'y'], verbose_name='Токен'),
        ),
    ]
