# Generated by Django 2.1.2 on 2021-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False, verbose_name='Двух-факторка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='03:19', verbose_name='Время написания комментария'),
        ),
    ]
