# Generated by Django 2.1.2 on 2021-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211112_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='17:01', verbose_name='Время написания комментария'),
        ),
    ]
