# Generated by Django 3.2.4 on 2021-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='01:43', verbose_name='Время написания комментария'),
        ),
    ]
