# Generated by Django 2.1.2 on 2021-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211117_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='17:12', verbose_name='Время написания комментария'),
        ),
    ]
