# Generated by Django 2.1.2 on 2021-12-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211117_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default='', max_length=200, verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='00:46', verbose_name='Время написания комментария'),
        ),
    ]
