# Generated by Django 3.2.4 on 2021-09-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='04:35', verbose_name='Время написания комментария'),
        ),
    ]
