# Generated by Django 2.1.2 on 2021-12-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211207_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='23:38', verbose_name='Время написания комментария'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Телеграмм'),
        ),
    ]
