# Generated by Django 3.2.4 on 2021-09-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=30, verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(default='19:44', verbose_name='Время написания комментария'),
        ),
    ]
